#!/usr/bin/env python3.7
# -*- coding: utf-8 -*-

import RPi.GPIO as GPIO
import time

gbp_40 = 40 # PCM_DOUT pin 40
gbp_38 = 38 # PCM_DIN pin 38
gbp_36 = 36 # GPIO.BOARD pin 36
gbp_11 = 11 # GPIO.BOARD pin 11 with 3.3 VDC pin 1
gbp_8 = 8 # TxD pin 8

def setup():
    print(' ')
    GPIO.setmode(GPIO.BOARD)       # Numbers GPIOs by physical location

    GPIO.setup(gbp_40, GPIO.OUT)   # Set gbp_40 mode is output
    GPIO.output(gbp_40, GPIO.HIGH) # Set gbp_40 high(+3.3V) to off led
    GPIO.setup(gbp_38, GPIO.OUT)   # Set gbp_38 mode is output
    GPIO.output(gbp_38, GPIO.HIGH) # Set gbp_38 high(+3.3V) to off led
    GPIO.setup(gbp_36, GPIO.OUT)   # Set gbp_36 mode is output
    GPIO.output(gbp_36, GPIO.HIGH) # Set gbp_36 high(+3.3V) to off led
    GPIO.setup(gbp_11, GPIO.OUT)   # Set gbp_11 mode is output
    GPIO.output(gbp_11, GPIO.HIGH) # Set gbp_11 high(+3.3V) to off led
    GPIO.setup(gbp_8, GPIO.OUT)   # Set gbp_8 mode is output
    GPIO.output(gbp_8, GPIO.HIGH) # Set gbp_8 high(+3.3V) to off led

def loop():
    
    while True:
        
        print('\n[ON]')
        GPIO.output(gbp_40, GPIO.LOW) # Led on
        GPIO.output(gbp_38, GPIO.LOW) # Led on
        GPIO.output(gbp_36, GPIO.LOW) # Led on
        GPIO.output(gbp_11, GPIO.LOW) # Led on
        GPIO.output(gbp_8, GPIO.LOW) # Led OFF
        time.sleep(3)
        
        print('[OFF]')
        GPIO.output(gbp_40, GPIO.HIGH) # Led off
        GPIO.output(gbp_38, GPIO.HIGH) # Led off
        GPIO.output(gbp_36, GPIO.HIGH) # Led off
        GPIO.output(gbp_11, GPIO.HIGH) # Led off
        GPIO.output(gbp_8, GPIO.HIGH) # Led ON
        time.sleep(2)

def destroy():
    
    GPIO.output(gbp_40, GPIO.HIGH) # Led off
    GPIO.output(gbp_38, GPIO.HIGH) # Led off
    GPIO.output(gbp_36, GPIO.HIGH) # Led off
    GPIO.output(gbp_11, GPIO.HIGH) # Turn off
    GPIO.output(gbp_8, GPIO.HIGH) # Turn off
    GPIO.cleanup()
    
    if __name__ == '__main__':
        setup()
    try:
        loop()
    except KeyboardInterrupt:
        destroy()

setup()
loop()
